<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:ship="http://docs.eebus.org/ship/exp/V1_X_ext_1__V1_0_b4/xsd"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://docs.eebus.org/ship/exp/V1_X_ext_1__V1_0_b4/xsd"
    elementFormDefault="qualified">
	<xs:include schemaLocation="SHIP_TS_TransferProtocol.xsd"/>
	<xs:element name="ShipMessage">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="MsgTypeControlGroup">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="connectionHello" type="ConnectionHello"/>
							<xs:element name="messageProtocolHandshake" type="MessageProtocolHandshake"/>
							<xs:element name="messageProtocolHandshakeError" type="MessageProtocolHandshakeError"/>
							<xs:element name="connectionPinState" type="ConnectionPinState"/>
							<xs:element name="connectionPinInput" type="ConnectionPinInput"/>
							<xs:element name="connectionPinError" type="ConnectionPinError"/>
							<xs:element name="accessMethodsRequest" type="AccessMethodsRequestType"/>
							<xs:element name="accessMethods" type="AccessMethodsType"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="MsgTypeEndGroup">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="connectionClose" type="ConnectionClose"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="MsgTypeDataGroup">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="data" type="Data"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

