/*
 *     Copyright KEO GmbH  - All rights reserved!
 *
 *     This software is protected by the inclusion of the above copyright
 * notice.
 *     This software may not be provided or otherwise made available to, or used
 *     by, any other person. No title to or ownership of the software is hereby
 *     transferred. The information contained in this document is considered the
 *     @b confidential and @b proprietary information of KEO GmbH
 *     and may not be disclosed or discussed with anyone who is not employed by
 *     KEO GmbH, unless the individual or company
 *     - has an express need to know such information, and
 *     - disclosure of information is subject to the terms of a duly
 *     executed "Confidentiality and Non-Disclosure Agreement" between
 *     KEO GmbH and the individual or company.
 */

#ifndef KEO_DATAGRAM_CORE_DATAELEMENTS_H_
#define KEO_DATAGRAM_CORE_DATAELEMENTS_H_

#include <map>
#include <memory>
#include <string>

#include <keo_datagram/core/KeoJsonTransformable.h>
#include <keo_datagram/core/xs_types.h>

namespace keo_datagram {

/** @addtogroup SpineDatagramCore
 * @{
 */

class DataElements;

//! typedef for non-const smart pointer type DataElements
using DataElementsPtr = std::shared_ptr<DataElements>;

//! typedef for const type DataElements
using DataElementsConst = const DataElements;

//! typedef for const type DataElements
using DataElementsConstPtr = std::shared_ptr<DataElementsConst>;

/**
 * Abstract base class for all DataElements.
 */
class DataElements : public KeoJsonTransformable {
public:
  //! Enumeration DataElements::Type
  enum class Type {
    UNDEFINED,
    ACTUATOR_LEVEL_DATA_ELEMENTS_TYPE,
    ACTUATOR_LEVEL_DESCRIPTION_DATA_ELEMENTS_TYPE,
    ACTUATOR_SWITCH_DATA_ELEMENTS_TYPE,
    ACTUATOR_SWITCH_DESCRIPTION_DATA_ELEMENTS_TYPE,
    ALARM_DATA_ELEMENTS_TYPE,
    BILL_CONSTRAINTS_DATA_ELEMENTS_TYPE,
    BILL_DATA_ELEMENTS_TYPE,
    BILL_DESCRIPTION_DATA_ELEMENTS_TYPE,
    BINDING_MANAGEMENT_DELETE_CALL_ELEMENTS_TYPE,
    BINDING_MANAGEMENT_ENTRY_DATA_ELEMENTS_TYPE,
    BINDING_MANAGEMENT_REQUEST_CALL_ELEMENTS_TYPE,
    COMMODITY_DATA_ELEMENTS_TYPE,
    DATA_TUNNELING_CALL_ELEMENTS_TYPE,
    DEVICE_CLASSIFICATION_MANUFACTURER_DATA_ELEMENTS_TYPE,
    DEVICE_CLASSIFICATION_USER_DATA_ELEMENTS_TYPE,
    DEVICE_CONFIGURATION_KEY_VALUE_CONSTRAINTS_DATA_ELEMENTS_TYPE,
    DEVICE_CONFIGURATION_KEY_VALUE_DATA_ELEMENTS_TYPE,
    DEVICE_CONFIGURATION_KEY_VALUE_DESCRIPTION_DATA_ELEMENTS_TYPE,
    DEVICE_DIAGNOSIS_HEARTBEAT_DATA_ELEMENTS_TYPE,
    DEVICE_DIAGNOSIS_SERVICE_DATA_ELEMENTS_TYPE,
    DEVICE_DIAGNOSIS_STATE_DATA_ELEMENTS_TYPE,
    DIRECT_CONTROL_ACTIVITY_DATA_ELEMENTS_TYPE,
    DIRECT_CONTROL_DESCRIPTION_DATA_ELEMENTS_TYPE,
    ELECTRICAL_CONNECTION_DESCRIPTION_DATA_ELEMENTS_TYPE,
    ELECTRICAL_CONNECTION_PARAMETER_DESCRIPTION_DATA_ELEMENTS_TYPE,
    ELECTRICAL_CONNECTION_PERMITTED_VALUE_SET_DATA_ELEMENTS_TYPE,
    ELECTRICAL_CONNECTION_STATE_DATA_ELEMENTS_TYPE,
    HVAC_OPERATION_MODE_DESCRIPTION_DATA_ELEMENTS_TYPE,
    HVAC_OVERRUN_DATA_ELEMENTS_TYPE,
    HVAC_OVERRUN_DESCRIPTION_DATA_ELEMENTS_TYPE,
    HVAC_SYSTEM_FUNCTION_DATA_ELEMENTS_TYPE,
    HVAC_SYSTEM_FUNCTION_DESCRIPTION_DATA_ELEMENTS_TYPE,
    HVAC_SYSTEM_FUNCTION_OPERATION_MODE_RELATION_DATA_ELEMENTS_TYPE,
    HVAC_SYSTEM_FUNCTION_POWER_SEQUENCE_RELATION_DATA_ELEMENTS_TYPE,
    HVAC_SYSTEM_FUNCTION_SETPOINT_RELATION_DATA_ELEMENTS_TYPE,
    IDENTIFICATION_DATA_ELEMENTS_TYPE,
    INCENTIVE_DATA_ELEMENTS_TYPE,
    INCENTIVE_DESCRIPTION_DATA_ELEMENTS_TYPE,
    INCENTIVE_TABLE_CONSTRAINTS_DATA_ELEMENTS_TYPE,
    INCENTIVE_TABLE_DATA_ELEMENTS_TYPE,
    INCENTIVE_TABLE_DESCRIPTION_DATA_ELEMENTS_TYPE,
    LOAD_CONTROL_EVENT_DATA_ELEMENTS_TYPE,
    LOAD_CONTROL_LIMIT_CONSTRAINTS_DATA_ELEMENTS_TYPE,
    LOAD_CONTROL_LIMIT_DATA_ELEMENTS_TYPE,
    LOAD_CONTROL_LIMIT_DESCRIPTION_DATA_ELEMENTS_TYPE,
    LOAD_CONTROL_NODE_DATA_ELEMENTS_TYPE,
    LOAD_CONTROL_STATE_DATA_ELEMENTS_TYPE,
    MEASUREMENT_CONSTRAINTS_DATA_ELEMENTS_TYPE,
    MEASUREMENT_DATA_ELEMENTS_TYPE,
    MEASUREMENT_DESCRIPTION_DATA_ELEMENTS_TYPE,
    MEASUREMENT_THRESHOLD_RELATION_DATA_ELEMENTS_TYPE,
    MESSAGING_DATA_ELEMENTS_TYPE,
    NETWORK_MANAGEMENT_ABORT_CALL_ELEMENTS_TYPE,
    NETWORK_MANAGEMENT_ADD_NODE_CALL_ELEMENTS_TYPE,
    NETWORK_MANAGEMENT_DEVICE_DESCRIPTION_DATA_ELEMENTS_TYPE,
    NETWORK_MANAGEMENT_DISCOVER_CALL_ELEMENTS_TYPE,
    NETWORK_MANAGEMENT_ENTITY_DESCRIPTION_DATA_ELEMENTS_TYPE,
    NETWORK_MANAGEMENT_FEATURE_DESCRIPTION_DATA_ELEMENTS_TYPE,
    NETWORK_MANAGEMENT_JOINING_MODE_DATA_ELEMENTS_TYPE,
    NETWORK_MANAGEMENT_MODIFY_NODE_CALL_ELEMENTS_TYPE,
    NETWORK_MANAGEMENT_PROCESS_STATE_DATA_ELEMENTS_TYPE,
    NETWORK_MANAGEMENT_REMOVE_NODE_CALL_ELEMENTS_TYPE,
    NETWORK_MANAGEMENT_REPORT_CANDIDATE_DATA_ELEMENTS_TYPE,
    NETWORK_MANAGEMENT_SCAN_NETWORK_CALL_ELEMENTS_TYPE,
    NODE_MANAGEMENT_BINDING_DATA_ELEMENTS_TYPE,
    NODE_MANAGEMENT_BINDING_DELETE_CALL_ELEMENTS_TYPE,
    NODE_MANAGEMENT_BINDING_REQUEST_CALL_ELEMENTS_TYPE,
    NODE_MANAGEMENT_DESTINATION_DATA_ELEMENTS_TYPE,
    NODE_MANAGEMENT_DETAILED_DISCOVERY_DATA_ELEMENTS_TYPE,
    NODE_MANAGEMENT_SUBSCRIPTION_DATA_ELEMENTS_TYPE,
    NODE_MANAGEMENT_SUBSCRIPTION_DELETE_CALL_ELEMENTS_TYPE,
    NODE_MANAGEMENT_SUBSCRIPTION_REQUEST_CALL_ELEMENTS_TYPE,
    NODE_MANAGEMENT_USE_CASE_DATA_ELEMENTS_TYPE,
    OPERATING_CONSTRAINTS_DURATION_DATA_ELEMENTS_TYPE,
    OPERATING_CONSTRAINTS_INTERRUPT_DATA_ELEMENTS_TYPE,
    OPERATING_CONSTRAINTS_POWER_DESCRIPTION_DATA_ELEMENTS_TYPE,
    OPERATING_CONSTRAINTS_POWER_LEVEL_DATA_ELEMENTS_TYPE,
    OPERATING_CONSTRAINTS_POWER_RANGE_DATA_ELEMENTS_TYPE,
    OPERATING_CONSTRAINTS_RESUME_IMPLICATION_DATA_ELEMENTS_TYPE,
    POWER_SEQUENCE_ALTERNATIVES_RELATION_DATA_ELEMENTS_TYPE,
    POWER_SEQUENCE_DESCRIPTION_DATA_ELEMENTS_TYPE,
    POWER_SEQUENCE_NODE_SCHEDULE_INFORMATION_DATA_ELEMENTS_TYPE,
    POWER_SEQUENCE_PRICE_CALCULATION_REQUEST_CALL_ELEMENTS_TYPE,
    POWER_SEQUENCE_PRICE_DATA_ELEMENTS_TYPE,
    POWER_SEQUENCE_SCHEDULE_CONFIGURATION_REQUEST_CALL_ELEMENTS_TYPE,
    POWER_SEQUENCE_SCHEDULE_CONSTRAINTS_DATA_ELEMENTS_TYPE,
    POWER_SEQUENCE_SCHEDULE_DATA_ELEMENTS_TYPE,
    POWER_SEQUENCE_SCHEDULE_PREFERENCE_DATA_ELEMENTS_TYPE,
    POWER_SEQUENCE_STATE_DATA_ELEMENTS_TYPE,
    POWER_TIME_SLOT_SCHEDULE_CONSTRAINTS_DATA_ELEMENTS_TYPE,
    POWER_TIME_SLOT_SCHEDULE_DATA_ELEMENTS_TYPE,
    POWER_TIME_SLOT_VALUE_DATA_ELEMENTS_TYPE,
    SENSING_DATA_ELEMENTS_TYPE,
    SENSING_DESCRIPTION_DATA_ELEMENTS_TYPE,
    SETPOINT_CONSTRAINTS_DATA_ELEMENTS_TYPE,
    SETPOINT_DATA_ELEMENTS_TYPE,
    SETPOINT_DESCRIPTION_DATA_ELEMENTS_TYPE,
    SMART_ENERGY_MANAGEMENT_PS_CONFIGURATION_REQUEST_CALL_ELEMENTS_TYPE,
    SMART_ENERGY_MANAGEMENT_PS_DATA_ELEMENTS_TYPE,
    SMART_ENERGY_MANAGEMENT_PS_PRICE_CALCULATION_REQUEST_CALL_ELEMENTS_TYPE,
    SMART_ENERGY_MANAGEMENT_PS_PRICE_DATA_ELEMENTS_TYPE,
    SPECIFICATION_VERSION_DATA_ELEMENTS_TYPE,
    SUBSCRIPTION_MANAGEMENT_DELETE_CALL_ELEMENTS_TYPE,
    SUBSCRIPTION_MANAGEMENT_ENTRY_DATA_ELEMENTS_TYPE,
    SUBSCRIPTION_MANAGEMENT_REQUEST_CALL_ELEMENTS_TYPE,
    SUPPLY_CONDITION_DATA_ELEMENTS_TYPE,
    SUPPLY_CONDITION_DESCRIPTION_DATA_ELEMENTS_TYPE,
    SUPPLY_CONDITION_THRESHOLD_RELATION_DATA_ELEMENTS_TYPE,
    TARIFF_BOUNDARY_RELATION_DATA_ELEMENTS_TYPE,
    TARIFF_DATA_ELEMENTS_TYPE,
    TARIFF_DESCRIPTION_DATA_ELEMENTS_TYPE,
    TARIFF_OVERALL_CONSTRAINTS_DATA_ELEMENTS_TYPE,
    TARIFF_TIER_RELATION_DATA_ELEMENTS_TYPE,
    TASK_MANAGEMENT_JOB_DATA_ELEMENTS_TYPE,
    TASK_MANAGEMENT_JOB_DESCRIPTION_DATA_ELEMENTS_TYPE,
    TASK_MANAGEMENT_JOB_RELATION_DATA_ELEMENTS_TYPE,
    TASK_MANAGEMENT_OVERVIEW_DATA_ELEMENTS_TYPE,
    THRESHOLD_CONSTRAINTS_DATA_ELEMENTS_TYPE,
    THRESHOLD_DATA_ELEMENTS_TYPE,
    THRESHOLD_DESCRIPTION_DATA_ELEMENTS_TYPE,
    TIER_BOUNDARY_DATA_ELEMENTS_TYPE,
    TIER_BOUNDARY_DESCRIPTION_DATA_ELEMENTS_TYPE,
    TIER_DATA_ELEMENTS_TYPE,
    TIER_DESCRIPTION_DATA_ELEMENTS_TYPE,
    TIER_INCENTIVE_RELATION_DATA_ELEMENTS_TYPE,
    TIME_DISTRIBUTOR_DATA_ELEMENTS_TYPE,
    TIME_DISTRIBUTOR_ENQUIRY_CALL_ELEMENTS_TYPE,
    TIME_INFORMATION_DATA_ELEMENTS_TYPE,
    TIME_PRECISION_DATA_ELEMENTS_TYPE,
    TIME_SERIES_CONSTRAINTS_DATA_ELEMENTS_TYPE,
    TIME_SERIES_DATA_ELEMENTS_TYPE,
    TIME_SERIES_DESCRIPTION_DATA_ELEMENTS_TYPE,
    TIME_TABLE_CONSTRAINTS_DATA_ELEMENTS_TYPE,
    TIME_TABLE_DATA_ELEMENTS_TYPE,
    TIME_TABLE_DESCRIPTION_DATA_ELEMENTS_TYPE,
    USE_CASE_INFORMATION_DATA_ELEMENTS_TYPE

  };

  /**
   * Get the type of this instance.
   * @return the type of this instance or UNDEFINED
   */
  virtual DataElements::Type getDataType() const = 0;

  /**
   * Checks if this instance is empty.
   * @return true, if no member is set
   */
  virtual bool isEmpty() const = 0;

  /**
   * Returns a copy of this instance.
   */
  virtual DataElementsPtr clone() const = 0;

  /**
   * Convert a DataElements::Type to a string.
   * @param type a type
   * @return the corresponding type or UNDEFINED
   */
  static std::string getStringFromType(DataElements::Type type);

  /**
   * Convert a string to a DataElements::Type.
   * @param type a string representing a type
   * @return the corresponding type or UNDEFINED
   */
  static DataElements::Type getTypeFromString(const std::string &type);

private:
  static std::map<std::string, DataElements::Type> STRING_TO_TYPE;
};

/** @}
 */

} // namespace keo_datagram

#endif // KEO_DATAGRAM_CORE_DATAELEMENTS_H_
