

set(CPACK_COMPONENT_BIN_GROUP "bin")
set(CPACK_COMPONENT_DEV_GROUP "dev")
set(CPACK_COMPONENT_DOC_GROUP "doc")
set(CPACK_COMPONENT_SDK_GROUP "sdk")
set(CPACK_COMPONENT_SRC_GROUP "src")
set(CPACK_COMPONENTS_ALL "bin;dev;doc;sdk;src")
