@startuml
participant Application
participant ShipStack
participant ShipControl
participant ShipConnection
participant "TransportConnectionHandler" as connectionHandler
participant "connectionHandlerListener\n(Distributor)" as distributor
participant "mainDevice\n(SmartDevice)" as mainDevice
participant entityHandler
participant entity
participant feature
participant "primaryNodeManagementFeature\n(PrimaryNodelManagementFeature)" as primaryNodeManagementFeature

Application -> Application : shipControl= new ShipControl(DeviceCallbackInterface)\nshipControl::initialize(connectionHandler)

ShipStack -> ShipControl: requestNodeConnect()
	ShipControl -> ShipControl: new ShipConnection(connectionHandler)

	ShipControl -> ShipConnection: onConnect()
	ShipControl <-- ShipConnection

	ShipControl -> ShipConnection: onDataExchangedEnabled()
		ShipConnection -> connectionHandler: addConnection()\n(TransportConnectionHandlerInterface)
		connectionHandler -> connectionHandler: insert\nconnection
	                connectionHandler -> distributor: announceDevice()\n(ConnectionToDistributorInterface)
			distributor -> mainDevice: announceDevice()\n(DistributorToDeviceInterface)
				mainDevice->mainDevice: add PrimaryNodeManagementEvent(NODE_REGISTERED_EVENT)
                                activate mainDevice
			distributor <-- mainDevice
	                connectionHandler <-- distributor
		ShipConnection <-- connectionHandler
	ShipControl <-- ShipConnection
ShipStack <-- ShipControl
				mainDevice -> entityHandler: getNodeManagementFeature()
				mainDevice <-- entityHandler
				mainDevice -> primaryNodeManagementFeature:nodeRegisteredEvent()
				primaryNodeManagementFeature -> primaryNodeManagementFeature: sendPendingMessage(NodeManagementDetailedDiscoveryRequest)\nadd pending message

				note over primaryNodeManagementFeature
				Send path not visualized
				end note

				mainDevice <-- primaryNodeManagementFeature
                                deactivate mainDevice
== reply ==

ShipStack -> ShipControl: datagramAvailable()
	ShipControl -> ShipConnection: onMessage()
		ShipConnection -> ShipConnection: decode JSON
		ShipConnection -> connectionHandler: onDatagram()\n(TransportConnectionHandlerInterface)
	                connectionHandler -> distributor: receivedDatagram()\n(ConnectionToDistributorInterface)

				distributor -> mainDevice: receivedDatagram()\n(DistributorToDeviceInterface)
					mainDevice->mainDevice: add DatagramEvent()
                                	activate mainDevice
				distributor <-- mainDevice
	                connectionHandler <-- distributor
		ShipConnection <-- connectionHandler
	ShipControl <-- ShipConnection
ShipStack <-- ShipControl

				mainDevice -> mainDevice:datagramEvent()
				activate mainDevice
					note over mainDevice
					parse payload
					end note
					mainDevice -> entityHandler: handleReplyDatagram()
						entityHandler -> entity: handleReplyDatagram()

							entity ->  feature:receivePendingDatagram()
							activate feature

								feature ->  primaryNodeManagementFeature:handlePendingDatagramDefault()
								activate primaryNodeManagementFeature

									primaryNodeManagementFeature -> primaryNodeManagementFeature : handleNodeManagementDetailedDiscoveryReply
									activate primaryNodeManagementFeature
										primaryNodeManagementFeature -> mainDevice : addDevice(dd, id)\nSendDatagramListener
										activate mainDevice

										note over mainDevice
											The deviceHandler creates and stores a new ConnectedDevice
										end note
										mainDevice->mainDevice: deviceHandler::addDevice(dd,id)
										
										mainDevice -> Application: connected(dd,id)\n(DeviceCallbackInterface)
										mainDevice <-- Application
										
										mainDevice-->primaryNodeManagementFeature
										deactivate mainDevice


		                                                        	primaryNodeManagementFeature -> primaryNodeManagementFeature: sendDestinationListRequest()
										
										
									primaryNodeManagementFeature <-- primaryNodeManagementFeature
									deactivate primaryNodeManagementFeature


								feature <--  primaryNodeManagementFeature
								deactivate primaryNodeManagementFeature

							entity <-- feature
							deactivate feature


						entityHandler <-- entity
					mainDevice <-- entityHandler
				deactivate mainDevice


				

                                deactivate mainDevice


@enduml

