 * @startuml
 * () "DistributorDeviceInterface" as DistDevInterface
 * () "DeviceDistributorInterface" as DevDistInterface
 * [distributor] as "Distributor"
 * [device] as "SmartDevice"
 * 
 * [distributor] -- DistDevInterface
 * [device] --  DevDistInterface
 * note top of [device]
 *   Acts as 'main device'
 * end note
 * [device] ..>  DistDevInterface: use
 * [distributor] ..>  DevDistInterface: use
 * @enduml

