 * @startuml
 * object "SmartDeviceApplication" as application
 * object "Configuration" as config
 * object "Distributor" as distributor
 * object "SmartDevice" as device
 * object "XYZ" as xyz
 * object "ShipConnectionHandler" as connectionhandler
 * object "ShipConnectionCreator" as connectioncreator
 * object "ShipDriver" as shipdriver
 * shipdriver *-- connectioncreator 
 * application *-- shipdriver
 * application *-- device 
 * application *-- distributor
 * application *-- config
 * distributor *-- connectionhandler
 * @enduml

