/*
 *     Copyright KEO GmbH  - All rights reserved!
 *
 *     This software is protected by the inclusion of the above copyright
 * notice.
 *     This software may not be provided or otherwise made available to, or used
 *     by, any other person. No title to or ownership of the software is hereby
 *     transferred. The information contained in this document is considered the
 *     @b confidential and @b proprietary information of KEO GmbH
 *     and may not be disclosed or discussed with anyone who is not employed by
 *     KEO GmbH, unless the individual or company
 *     - has an express need to know such information, and
 *     - disclosure of information is subject to the terms of a duly
 *     executed "Confidentiality and Non-Disclosure Agreement" between
 *     KEO GmbH and the individual or company.
 */

#ifndef KEO_DATAGRAM_CORE_DATASELECTORS_H_
#define KEO_DATAGRAM_CORE_DATASELECTORS_H_

#include <map>
#include <memory>
#include <string>

#include <keo_datagram/core/KeoJsonTransformable.h>
#include <keo_datagram/core/xs_types.h>

namespace keo_datagram {

/** @addtogroup SpineDatagramCore
 * @{
 */

class DataSelectors;

//! typedef for non-const smart pointer type DataSelectors
using DataSelectorsPtr = std::shared_ptr<DataSelectors>;

//! typedef for const type DataSelectors
using DataSelectorsConst = const DataSelectors;

//! typedef for const type DataSelectors
using DataSelectorsConstPtr = std::shared_ptr<DataSelectorsConst>;

/**
 * Abstract base class for all DataSelectors.
 */
class DataSelectors : public KeoJsonTransformable {
public:
  //! Enumeration DataSelectors::Type
  enum class Type {
    UNDEFINED,
    ALARM_LIST_DATA_SELECTORS_TYPE,
    BILL_CONSTRAINTS_LIST_DATA_SELECTORS_TYPE,
    BILL_DESCRIPTION_LIST_DATA_SELECTORS_TYPE,
    BILL_LIST_DATA_SELECTORS_TYPE,
    BINDING_MANAGEMENT_ENTRY_LIST_DATA_SELECTORS_TYPE,
    COMMODITY_LIST_DATA_SELECTORS_TYPE,
    DEVICE_CONFIGURATION_KEY_VALUE_CONSTRAINTS_LIST_DATA_SELECTORS_TYPE,
    DEVICE_CONFIGURATION_KEY_VALUE_DESCRIPTION_LIST_DATA_SELECTORS_TYPE,
    DEVICE_CONFIGURATION_KEY_VALUE_LIST_DATA_SELECTORS_TYPE,
    DIRECT_CONTROL_ACTIVITY_LIST_DATA_SELECTORS_TYPE,
    ELECTRICAL_CONNECTION_DESCRIPTION_LIST_DATA_SELECTORS_TYPE,
    ELECTRICAL_CONNECTION_PARAMETER_DESCRIPTION_LIST_DATA_SELECTORS_TYPE,
    ELECTRICAL_CONNECTION_PERMITTED_VALUE_SET_LIST_DATA_SELECTORS_TYPE,
    ELECTRICAL_CONNECTION_STATE_LIST_DATA_SELECTORS_TYPE,
    HVAC_OPERATION_MODE_DESCRIPTION_LIST_DATA_SELECTORS_TYPE,
    HVAC_OVERRUN_DESCRIPTION_LIST_DATA_SELECTORS_TYPE,
    HVAC_OVERRUN_LIST_DATA_SELECTORS_TYPE,
    HVAC_SYSTEM_FUNCTION_DESCRIPTION_LIST_DATA_SELECTORS_TYPE,
    HVAC_SYSTEM_FUNCTION_LIST_DATA_SELECTORS_TYPE,
    HVAC_SYSTEM_FUNCTION_OPERATION_MODE_RELATION_LIST_DATA_SELECTORS_TYPE,
    HVAC_SYSTEM_FUNCTION_POWER_SEQUENCE_RELATION_LIST_DATA_SELECTORS_TYPE,
    HVAC_SYSTEM_FUNCTION_SETPOINT_RELATION_LIST_DATA_SELECTORS_TYPE,
    IDENTIFICATION_LIST_DATA_SELECTORS_TYPE,
    INCENTIVE_DESCRIPTION_LIST_DATA_SELECTORS_TYPE,
    INCENTIVE_LIST_DATA_SELECTORS_TYPE,
    INCENTIVE_TABLE_CONSTRAINTS_DATA_SELECTORS_TYPE,
    INCENTIVE_TABLE_DATA_SELECTORS_TYPE,
    INCENTIVE_TABLE_DESCRIPTION_DATA_SELECTORS_TYPE,
    LOAD_CONTROL_EVENT_LIST_DATA_SELECTORS_TYPE,
    LOAD_CONTROL_LIMIT_CONSTRAINTS_LIST_DATA_SELECTORS_TYPE,
    LOAD_CONTROL_LIMIT_DESCRIPTION_LIST_DATA_SELECTORS_TYPE,
    LOAD_CONTROL_LIMIT_LIST_DATA_SELECTORS_TYPE,
    LOAD_CONTROL_STATE_LIST_DATA_SELECTORS_TYPE,
    MEASUREMENT_CONSTRAINTS_LIST_DATA_SELECTORS_TYPE,
    MEASUREMENT_DESCRIPTION_LIST_DATA_SELECTORS_TYPE,
    MEASUREMENT_LIST_DATA_SELECTORS_TYPE,
    MEASUREMENT_THRESHOLD_RELATION_LIST_DATA_SELECTORS_TYPE,
    MESSAGING_LIST_DATA_SELECTORS_TYPE,
    NETWORK_MANAGEMENT_DEVICE_DESCRIPTION_LIST_DATA_SELECTORS_TYPE,
    NETWORK_MANAGEMENT_ENTITY_DESCRIPTION_LIST_DATA_SELECTORS_TYPE,
    NETWORK_MANAGEMENT_FEATURE_DESCRIPTION_LIST_DATA_SELECTORS_TYPE,
    NODE_MANAGEMENT_BINDING_DATA_SELECTORS_TYPE,
    NODE_MANAGEMENT_DESTINATION_LIST_DATA_SELECTORS_TYPE,
    NODE_MANAGEMENT_DETAILED_DISCOVERY_DATA_SELECTORS_TYPE,
    NODE_MANAGEMENT_SUBSCRIPTION_DATA_SELECTORS_TYPE,
    NODE_MANAGEMENT_USE_CASE_DATA_SELECTORS_TYPE,
    OPERATING_CONSTRAINTS_DURATION_LIST_DATA_SELECTORS_TYPE,
    OPERATING_CONSTRAINTS_INTERRUPT_LIST_DATA_SELECTORS_TYPE,
    OPERATING_CONSTRAINTS_POWER_DESCRIPTION_LIST_DATA_SELECTORS_TYPE,
    OPERATING_CONSTRAINTS_POWER_LEVEL_LIST_DATA_SELECTORS_TYPE,
    OPERATING_CONSTRAINTS_POWER_RANGE_LIST_DATA_SELECTORS_TYPE,
    OPERATING_CONSTRAINTS_RESUME_IMPLICATION_LIST_DATA_SELECTORS_TYPE,
    POWER_SEQUENCE_ALTERNATIVES_RELATION_LIST_DATA_SELECTORS_TYPE,
    POWER_SEQUENCE_DESCRIPTION_LIST_DATA_SELECTORS_TYPE,
    POWER_SEQUENCE_PRICE_LIST_DATA_SELECTORS_TYPE,
    POWER_SEQUENCE_SCHEDULE_CONSTRAINTS_LIST_DATA_SELECTORS_TYPE,
    POWER_SEQUENCE_SCHEDULE_LIST_DATA_SELECTORS_TYPE,
    POWER_SEQUENCE_SCHEDULE_PREFERENCE_LIST_DATA_SELECTORS_TYPE,
    POWER_SEQUENCE_STATE_LIST_DATA_SELECTORS_TYPE,
    POWER_TIME_SLOT_SCHEDULE_CONSTRAINTS_LIST_DATA_SELECTORS_TYPE,
    POWER_TIME_SLOT_SCHEDULE_LIST_DATA_SELECTORS_TYPE,
    POWER_TIME_SLOT_VALUE_LIST_DATA_SELECTORS_TYPE,
    SENSING_LIST_DATA_SELECTORS_TYPE,
    SETPOINT_CONSTRAINTS_LIST_DATA_SELECTORS_TYPE,
    SETPOINT_DESCRIPTION_LIST_DATA_SELECTORS_TYPE,
    SETPOINT_LIST_DATA_SELECTORS_TYPE,
    SMART_ENERGY_MANAGEMENT_PS_DATA_SELECTORS_TYPE,
    SMART_ENERGY_MANAGEMENT_PS_PRICE_DATA_SELECTORS_TYPE,
    SPECIFICATION_VERSION_LIST_DATA_SELECTORS_TYPE,
    SUBSCRIPTION_MANAGEMENT_ENTRY_LIST_DATA_SELECTORS_TYPE,
    SUPPLY_CONDITION_DESCRIPTION_LIST_DATA_SELECTORS_TYPE,
    SUPPLY_CONDITION_LIST_DATA_SELECTORS_TYPE,
    SUPPLY_CONDITION_THRESHOLD_RELATION_LIST_DATA_SELECTORS_TYPE,
    TARIFF_BOUNDARY_RELATION_LIST_DATA_SELECTORS_TYPE,
    TARIFF_DESCRIPTION_LIST_DATA_SELECTORS_TYPE,
    TARIFF_LIST_DATA_SELECTORS_TYPE,
    TARIFF_TIER_RELATION_LIST_DATA_SELECTORS_TYPE,
    TASK_MANAGEMENT_JOB_DESCRIPTION_LIST_DATA_SELECTORS_TYPE,
    TASK_MANAGEMENT_JOB_LIST_DATA_SELECTORS_TYPE,
    TASK_MANAGEMENT_JOB_RELATION_LIST_DATA_SELECTORS_TYPE,
    THRESHOLD_CONSTRAINTS_LIST_DATA_SELECTORS_TYPE,
    THRESHOLD_DESCRIPTION_LIST_DATA_SELECTORS_TYPE,
    THRESHOLD_LIST_DATA_SELECTORS_TYPE,
    TIER_BOUNDARY_DESCRIPTION_LIST_DATA_SELECTORS_TYPE,
    TIER_BOUNDARY_LIST_DATA_SELECTORS_TYPE,
    TIER_DESCRIPTION_LIST_DATA_SELECTORS_TYPE,
    TIER_INCENTIVE_RELATION_LIST_DATA_SELECTORS_TYPE,
    TIER_LIST_DATA_SELECTORS_TYPE,
    TIME_SERIES_CONSTRAINTS_LIST_DATA_SELECTORS_TYPE,
    TIME_SERIES_DESCRIPTION_LIST_DATA_SELECTORS_TYPE,
    TIME_SERIES_LIST_DATA_SELECTORS_TYPE,
    TIME_TABLE_CONSTRAINTS_LIST_DATA_SELECTORS_TYPE,
    TIME_TABLE_DESCRIPTION_LIST_DATA_SELECTORS_TYPE,
    TIME_TABLE_LIST_DATA_SELECTORS_TYPE,
    USE_CASE_INFORMATION_LIST_DATA_SELECTORS_TYPE

  };

  /**
   * Get the type of this instance.
   * @return the type of this instance or UNDEFINED
   */
  virtual DataSelectors::Type getDataType() const = 0;

  /**
   * Checks if this instance is empty.
   * @return true, if no member is set
   */
  virtual bool isEmpty() const = 0;

  /**
   * Returns a copy of this instance.
   */
  virtual DataSelectorsPtr clone() const = 0;

  /**
   * Convert a DataSelectors::Type to a string.
   * @param type a type
   * @return the corresponding type or UNDEFINED
   */
  static std::string getStringFromType(DataSelectors::Type type);

  /**
   * Convert a string to a DataSelectors::Type.
   * @param type a string representing a type
   * @return the corresponding type or UNDEFINED
   */
  static DataSelectors::Type getTypeFromString(const std::string &type);

private:
  static std::map<std::string, DataSelectors::Type> STRING_TO_TYPE;
};

/** @}
 */

} // namespace keo_datagram

#endif // KEO_DATAGRAM_CORE_DATASELECTORS_H_
