/*
 *     Copyright KEO GmbH 2019 - All rights reserved!
 *
 *     This software is protected by the inclusion of the above copyright
 * notice.
 *     This software may not be provided or otherwise made available to, or used
 *     by, any other person. No title to or ownership of the software is hereby
 *     transferred. The information contained in this document is considered the
 *     @b confidential and @b proprietary information of KEO GmbH
 *     and may not be disclosed or discussed with anyone who is not employed by
 *     KEO GmbH, unless the individual or company
 *     - has an express need to know such information, and
 *     - disclosure of information is subject to the terms of a duly
 *     executed "Confidentiality and Non-Disclosure Agreement" between
 *     KEO GmbH and the individual or company.
 */

#ifndef KEO_DATAGRAM_CORE_FUNCTION_H_
#define KEO_DATAGRAM_CORE_FUNCTION_H_

#include <cstdint>
#include <string>

#include <keo_datagram/core/SpineEnumClass.h>

namespace keo_datagram {

/** @addtogroup SpineDatagramCore
 * @{
 */

/**
 * Declaration Function
 */
class Function : public ExtendableSpineEnum {
public:
  //! Number of possible enumeration values
  const static std::size_t MAX_ENUM = 137;

  //! Enumeration Function::Value
  enum class Value {
    UNDEFINED__ = -1,
    ACTUATOR_LEVEL_DATA,
    ACTUATOR_LEVEL_DESCRIPTION_DATA,
    ACTUATOR_SWITCH_DATA,
    ACTUATOR_SWITCH_DESCRIPTION_DATA,
    ALARM_LIST_DATA,
    BINDING_MANAGEMENT_DELETE_CALL,
    BINDING_MANAGEMENT_ENTRY_LIST_DATA,
    BINDING_MANAGEMENT_REQUEST_CALL,
    DATA_TUNNELING_CALL,
    DEVICE_CLASSIFICATION_MANUFACTURER_DATA,
    DEVICE_CLASSIFICATION_USER_DATA,
    DEVICE_DIAGNOSIS_HEARTBEAT_DATA,
    DEVICE_DIAGNOSIS_SERVICE_DATA,
    DEVICE_DIAGNOSIS_STATE_DATA,
    DIRECT_CONTROL_ACTIVITY_LIST_DATA,
    DIRECT_CONTROL_DESCRIPTION_DATA,
    ELECTRICAL_CONNECTION_DESCRIPTION_LIST_DATA,
    ELECTRICAL_CONNECTION_PARAMETER_DESCRIPTION_LIST_DATA,
    ELECTRICAL_CONNECTION_STATE_LIST_DATA,
    HVAC_OPERATION_MODE_DESCRIPTION_LIST_DATA,
    HVAC_OVERRUN_DESCRIPTION_LIST_DATA,
    HVAC_OVERRUN_LIST_DATA,
    HVAC_SYSTEM_FUNCTION_DESCRIPTION_LIST_DATA,
    HVAC_SYSTEM_FUNCTION_LIST_DATA,
    HVAC_SYSTEM_FUNCTION_OPERATION_MODE_RELATION_LIST_DATA,
    HVAC_SYSTEM_FUNCTION_POWER_SEQUENCE_RELATION_LIST_DATA,
    HVAC_SYSTEM_FUNCTION_SETPOINT_RELATION_LIST_DATA,
    LOAD_CONTROL_EVENT_LIST_DATA,
    LOAD_CONTROL_STATE_LIST_DATA,
    MEASUREMENT_CONSTRAINTS_LIST_DATA,
    MEASUREMENT_DESCRIPTION_LIST_DATA,
    MEASUREMENT_LIST_DATA,
    MEASUREMENT_THRESHOLD_RELATION_LIST_DATA,
    MESSAGING_LIST_DATA,
    NETWORK_MANAGEMENT_ABORT_CALL,
    NETWORK_MANAGEMENT_ADD_NODE_CALL,
    NETWORK_MANAGEMENT_DEVICE_DESCRIPTION_LIST_DATA,
    NETWORK_MANAGEMENT_DISCOVER_CALL,
    NETWORK_MANAGEMENT_ENTITY_DESCRIPTION_LIST_DATA,
    NETWORK_MANAGEMENT_FEATURE_DESCRIPTION_LIST_DATA,
    NETWORK_MANAGEMENT_JOINING_MODE_DATA,
    NETWORK_MANAGEMENT_MODIFY_NODE_CALL,
    NETWORK_MANAGEMENT_PROCESS_STATE_DATA,
    NETWORK_MANAGEMENT_REMOVE_NODE_CALL,
    NETWORK_MANAGEMENT_REPORT_CANDIDATE_DATA,
    NETWORK_MANAGEMENT_SCAN_NETWORK_CALL,
    NODE_MANAGEMENT_BINDING_DATA,
    NODE_MANAGEMENT_BINDING_DELETE_CALL,
    NODE_MANAGEMENT_BINDING_REQUEST_CALL,
    NODE_MANAGEMENT_DESTINATION_LIST_DATA,
    NODE_MANAGEMENT_DETAILED_DISCOVERY_DATA,
    NODE_MANAGEMENT_SUBSCRIPTION_DATA,
    NODE_MANAGEMENT_SUBSCRIPTION_DELETE_CALL,
    NODE_MANAGEMENT_SUBSCRIPTION_REQUEST_CALL,
    OPERATING_CONSTRAINTS_DURATION_LIST_DATA,
    OPERATING_CONSTRAINTS_INTERRUPT_LIST_DATA,
    OPERATING_CONSTRAINTS_POWER_DESCRIPTION_LIST_DATA,
    OPERATING_CONSTRAINTS_POWER_LEVEL_LIST_DATA,
    OPERATING_CONSTRAINTS_POWER_RANGE_LIST_DATA,
    OPERATING_CONSTRAINTS_RESUME_IMPLICATION_LIST_DATA,
    POWER_SEQUENCE_ALTERNATIVES_RELATION_LIST_DATA,
    POWER_SEQUENCE_DESCRIPTION_LIST_DATA,
    POWER_SEQUENCE_NODE_SCHEDULE_INFORMATION_DATA,
    POWER_SEQUENCE_PRICE_CALCULATION_REQUEST_CALL,
    POWER_SEQUENCE_PRICE_LIST_DATA,
    POWER_SEQUENCE_SCHEDULE_CONFIGURATION_REQUEST_CALL,
    POWER_SEQUENCE_SCHEDULE_CONSTRAINTS_LIST_DATA,
    POWER_SEQUENCE_SCHEDULE_LIST_DATA,
    POWER_SEQUENCE_SCHEDULE_PREFERENCE_LIST_DATA,
    POWER_SEQUENCE_STATE_LIST_DATA,
    POWER_TIME_SLOT_SCHEDULE_CONSTRAINTS_LIST_DATA,
    POWER_TIME_SLOT_SCHEDULE_LIST_DATA,
    POWER_TIME_SLOT_VALUE_LIST_DATA,
    RESULT_DATA,
    SENSING_DESCRIPTION_DATA,
    SENSING_LIST_DATA,
    SETPOINT_CONSTRAINTS_LIST_DATA,
    SETPOINT_DESCRIPTION_LIST_DATA,
    SETPOINT_LIST_DATA,
    SMART_ENERGY_MANAGEMENT_PS_CONFIGURATION_REQUEST_CALL,
    SMART_ENERGY_MANAGEMENT_PS_DATA,
    SMART_ENERGY_MANAGEMENT_PS_PRICE_CALCULATION_REQUEST_CALL,
    SMART_ENERGY_MANAGEMENT_PS_PRICE_DATA,
    SPECIFICATION_VERSION_LIST_DATA,
    SUBSCRIPTION_MANAGEMENT_DELETE_CALL,
    SUBSCRIPTION_MANAGEMENT_ENTRY_LIST_DATA,
    SUBSCRIPTION_MANAGEMENT_REQUEST_CALL,
    SUPPLY_CONDITION_DESCRIPTION_LIST_DATA,
    SUPPLY_CONDITION_LIST_DATA,
    SUPPLY_CONDITION_THRESHOLD_RELATION_LIST_DATA,
    TASK_MANAGEMENT_JOB_DESCRIPTION_LIST_DATA,
    TASK_MANAGEMENT_JOB_LIST_DATA,
    TASK_MANAGEMENT_JOB_RELATION_LIST_DATA,
    TASK_MANAGEMENT_OVERVIEW_DATA,
    THRESHOLD_CONSTRAINTS_LIST_DATA,
    THRESHOLD_DESCRIPTION_LIST_DATA,
    THRESHOLD_LIST_DATA,
    TIME_DISTRIBUTOR_DATA,
    TIME_DISTRIBUTOR_ENQUIRY_CALL,
    TIME_INFORMATION_DATA,
    TIME_PRECISION_DATA,
    TIME_TABLE_CONSTRAINTS_LIST_DATA,
    TIME_TABLE_DESCRIPTION_LIST_DATA,
    TIME_TABLE_LIST_DATA,
    DEVICE_CONFIGURATION_KEY_VALUE_CONSTRAINTS_LIST_DATA,
    DEVICE_CONFIGURATION_KEY_VALUE_LIST_DATA,
    DEVICE_CONFIGURATION_KEY_VALUE_DESCRIPTION_LIST_DATA,
    LOAD_CONTROL_LIMIT_CONSTRAINTS_LIST_DATA,
    LOAD_CONTROL_LIMIT_DESCRIPTION_LIST_DATA,
    LOAD_CONTROL_LIMIT_LIST_DATA,
    LOAD_CONTROL_NODE_DATA,
    TIME_SERIES_CONSTRAINTS_LIST_DATA,
    TIME_SERIES_DESCRIPTION_LIST_DATA,
    TIME_SERIES_LIST_DATA,
    TARIFF_OVERALL_CONSTRAINTS_DATA,
    TARIFF_LIST_DATA,
    TARIFF_BOUNDARY_RELATION_LIST_DATA,
    TARIFF_TIER_RELATION_LIST_DATA,
    TARIFF_DESCRIPTION_LIST_DATA,
    TIER_BOUNDARY_LIST_DATA,
    TIER_BOUNDARY_DESCRIPTION_LIST_DATA,
    COMMODITY_LIST_DATA,
    TIER_LIST_DATA,
    TIER_INCENTIVE_RELATION_LIST_DATA,
    TIER_DESCRIPTION_LIST_DATA,
    INCENTIVE_LIST_DATA,
    INCENTIVE_DESCRIPTION_LIST_DATA,
    INCENTIVE_TABLE_DATA,
    INCENTIVE_TABLE_DESCRIPTION_DATA,
    INCENTIVE_TABLE_CONSTRAINTS_DATA,
    ELECTRICAL_CONNECTION_PERMITTED_VALUE_SET_LIST_DATA,
    USE_CASE_INFORMATION_LIST_DATA,
    NODE_MANAGEMENT_USE_CASE_DATA,
    BILL_CONSTRAINTS_LIST_DATA,
    BILL_DESCRIPTION_LIST_DATA,
    BILL_LIST_DATA,
    IDENTIFICATION_LIST_DATA
  };

  /**
   * Constructs an instance with the value "undefined".
   */
  Function();

  /**
   * Constructs an instance and sets its value from enum value.
   * @param value the value of the new instance
   */
  Function(Function::Value value);

  /**
   * Constructs an instance and sets its value from string.
   * @param value the value of the new instance
   */
  Function(const std::string &value);

  /**
   * Constructs the enumeration value from string.
   * @returns An enumeration object created from the string
   */
  static Function fromString(const std::string &c_text);

  /**
   * Return struct object as string
   * @return enumeration object as string
   */
  std::string toString() const;

  /**
   * Set this enum object from string
   * @param c_text the string to set
   */
  bool setFromString(const std::string &c_text);

  /**
   * Return the value of this enumeration object.
   * @return enumeration value
   */
  Function::Value getValue() const;

  /**
   * Return the value of this enumeration object.
   * \deprecated Use getValue() instead.
   * @return enumeration value
   */
  Function::Value getData() const;

  /**
   * Comparison operator ==
   * @param other object to compare
   */
  bool operator==(const Function &other) const;

  /**
   * Comparison operator !=
   * @param other object to compare
   */
  bool operator!=(const Function &other) const;

private:
  std::size_t toNumber() const;

  bool setFromNumber(std::size_t c_number);

  Function::Value m_data;

  // Human-readable strings of the enum data type
  static const std::string enumToString[MAX_ENUM];
};

/**
 * \deprecated Use Function instead.
 */
using FunctionStruct = Function;

/** @}
 */

} // namespace keo_datagram

#endif // KEO_DATAGRAM_CORE_FUNCTION_H_