############################
# logging configuration
############################


## global

to_console=true
use_colors=true

to_file=false
filename=./logging.log

level=WARNING


## modules
[keo_util]
level=WARNING

[keo_ship_stack]
level=WARNING

[keo_ship_discovery]
level=WARNING

[keo_spine_transport]
level=INFO

[keo_spine]
level=INFO

[json_security_handler]
level=WARNING

[example_server]
level=TRACE


