include(FindPackageHandleStandardArgs)


message(STATUS "LIBRARY_PATH_PREFIX: ${LIBRARY_PATH_PREFIX}")
message(STATUS "LIB_SEARCH_OPTIONS: ${LIB_SEARCH_OPTIONS}")

find_path(
	AVAHI_INCLUDE_DIR
	NAMES avahi-client/client.h
)


find_library(
	AVAHI_COMMON_LIBRARY
	NAMES avahi-common
	PATH_SUFFIXES
	${LIBRARY_PATH_PREFIX}
	${LIB_SEARCH_OPTIONS}
)


find_library(
	AVAHI_CLIENT_LIBRARY
	NAMES avahi-client
	PATH_SUFFIXES
	${LIBRARY_PATH_PREFIX}
	${LIB_SEARCH_OPTIONS}
)


set(AVAHI_LIBRARIES ${AVAHI_CLIENT_LIBRARY} ${AVAHI_COMMON_LIBRARY})


find_package_handle_standard_args(
	AVAHI
	DEFAULT_MSG
	AVAHI_LIBRARIES AVAHI_INCLUDE_DIR
)


get_filename_component(AVAHI_LIBRARY_DIR ${AVAHI_CLIENT_LIBRARY}  DIRECTORY)
message(STATUS "AVAHI_LIBRARIES: ${AVAHI_LIBRARIES}")
message(STATUS "AVAHI_INCLUDE_DIR: ${AVAHI_INCLUDE_DIR}")


mark_as_advanced(
	AVAHI_INCLUDE_DIR
	AVAHI_LIBRARIES
)
